const type_to_image = {
    "ノーマル": "normal",
    "感情": "heart",
    "食べ物": "food",
    "植物": "plant",
    "社会": "social",
    "時間": "time",
    "工作": "craft",
    "芸術": "art",
    "機械": "machine",
    "遊び": "play",
    "暴力": "violence",
    "服飾": "cloth",
    "動物": "animal",
    "地名": "place",
    "人物": "person",
    "人体": "body",
    "理科": "science",
    "暴言": "abuse",
    "虫": "insect",
    "数学": "math",
    "医療": "medical",
    "宗教": "religion",
    "スポーツ": "sports",
    "物語": "story",
    "天気": "weather"
}
